### ISSUE TITLE
Error: React functionality 'useContext' is not available in this environment.

### ISSUE THREAD

**Issue by MiguelG97** [phryneas/rehackt#11]
I encountered this issue while integrating apollo client graphql in a nextjs app.

Apparently apollo is using rehackt npm package and somehow it's not exporting the useContext functionality:

![image](https://github.com/phryneas/rehackt/assets/78984964/75aa604b-ae18-40fb-839d-22e2c653587d)

this is my layout in nextjs:

```
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxContext>{children}</ReduxContext> */}

        <ReduxContext>
          <ApolloProvider client={client}>
            {children}
          </ApolloProvider>
        </ReduxContext>
      </body>
    </html>
  );
}
```

as soons as I wrap the content with the ApolloProvider, dialog throws that error

**Comment by phryneas** [comment]
Yes, that means that you are trying to do so in a Server Component, which cannot hold any context. Providers always have to be used within Client Components.

Generally, please use our package for the Next.js app directory and don't set up Apollo Client without it.
You can find setup instructions under https://github.com/apollographql/apollo-client-nextjs

**Comment by MiguelG97** [comment]
Interesting, that works too!

**Comment by phryneas** [comment]
Yes, it's currently the only supported way of using Apollo Client in Next.js - Next.js uses a lot of React features that are not making up a complete story (it uses streaming SSR, and React doesn't have an official way of injecting data into the stream yet) - so until React ships those missing features, we have to work around it in a way specific to the Next.js implementation.
